version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes: 
     - "/var/lib/postgresql/"
  django:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: "bash -c 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'"
    tty: true
  frontend:
    build: ./frontend
    # command: yarn start
    # entrypoint: "bash -c 'npm install && yarn start'"
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - django
    tty: true

volumes:
  node-modules:
